#!/bin/bash
# BABLO VPN - Installation Script
# For Ubuntu 22.04+

set -e

echo "=========================================="
echo "   BABLO VPN - Installation"
echo "=========================================="

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root: sudo bash install.sh"
    exit 1
fi

# Get server IP
SERVER_IP=$(curl -s ifconfig.me || hostname -I | awk '{print $1}')

# Prompt for domain
echo ""
read -p "Enter your domain (or press Enter to use IP $SERVER_IP): " DOMAIN
if [ -z "$DOMAIN" ]; then
    DOMAIN=$SERVER_IP
fi

# Prompt for password
echo ""
read -sp "Enter admin password for WireGuard UI: " ADMIN_PASSWORD
echo ""

# Update system
echo "[1/7] Updating system..."
apt update && apt upgrade -y

# Install Docker
echo "[2/7] Installing Docker..."
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
else
    echo "Docker already installed"
fi

# Install Docker Compose plugin
echo "[3/7] Checking Docker Compose..."
docker compose version || apt install -y docker-compose-plugin

# Install Git
echo "[4/7] Checking Git..."
apt install -y git

# Clone or update repository
echo "[5/7] Downloading project..."
if [ -d "/opt/bablo-vpn" ]; then
    cd /opt/bablo-vpn
    git pull origin main || true
else
    git clone https://github.com/trAIderai/BABLO-VPN.git /opt/bablo-vpn
    cd /opt/bablo-vpn
fi

# Generate password hash
echo "[6/7] Configuring environment..."
PASSWORD_HASH=$(docker run --rm ghcr.io/wg-easy/wg-easy:14 wgpw "$ADMIN_PASSWORD" 2>/dev/null | tail -1)
# Escape $ for docker-compose
PASSWORD_HASH_ESCAPED=$(echo "$PASSWORD_HASH" | sed 's/\$/\$\$/g')

# Create .env file
cat > /opt/bablo-vpn/.env << EOF
# BABLO VPN Configuration
# Generated by install.sh on $(date)

WG_HOST=$DOMAIN
PASSWORD_HASH=$PASSWORD_HASH_ESCAPED

# Optional: Cloudflare Turnstile (leave empty to disable CAPTCHA)
TURNSTILE_SITE_KEY=
TURNSTILE_SECRET_KEY=

# VLESS Reality Configuration
# These values need to be set after configuring 3x-ui panel
# See .env.example for instructions
VLESS_UUID=
REALITY_PUBLIC_KEY=
REALITY_SHORT_ID=
VLESS_PORT=8443
EOF

chmod 600 /opt/bablo-vpn/.env

# Configure firewall
echo "[7/7] Configuring firewall..."
if command -v ufw &> /dev/null; then
    ufw allow 22/tcp      # SSH
    ufw allow 80/tcp      # HTTP
    ufw allow 443/tcp     # HTTPS
    ufw allow 51820/udp   # WireGuard
    ufw allow 2053/tcp    # 3x-ui Admin Panel
    ufw allow 8443/tcp    # VLESS Reality
    ufw allow 8444/tcp    # Trojan Reality
    ufw allow 8445/udp    # Hysteria2
    echo "y" | ufw enable || true
fi

# Stop old containers
echo "=========================================="
echo "   Stopping old containers..."
echo "=========================================="
docker stop wg-easy caddy vpn-ui xray-ui adguard-home hysteria2 2>/dev/null || true
docker rm wg-easy caddy vpn-ui xray-ui adguard-home hysteria2 2>/dev/null || true

# Build and start containers
echo "=========================================="
echo "   Building and starting BABLO VPN..."
echo "=========================================="
docker compose build --no-cache
docker compose up -d

# Wait for startup
sleep 10

# Status
echo ""
echo "=========================================="
echo "   INSTALLATION COMPLETE!"
echo "=========================================="
echo ""
docker compose ps
echo ""
echo "=========== WireGuard VPN =============="
echo "Admin panel: https://$DOMAIN"
echo "WireGuard port: 51820/udp"
echo ""
echo "============ AdGuard Home =============="
echo "DNS: Active (port 53 via WireGuard)"
echo "Admin: http://$SERVER_IP:8053"
echo "Login: admin / admin (change in panel!)"
echo ""
echo "============= 3x-ui (Xray) ============="
echo "Panel: http://$SERVER_IP:2053"
echo "Login: admin"
echo "Password: admin"
echo "IMPORTANT: Change password immediately!"
echo ""
echo "Protocols:"
echo "  VLESS/Trojan: port 8443/tcp"
echo "  Hysteria2: port 8445/udp"
echo ""
echo "=========== NEXT STEPS ================="
echo "1. Open 3x-ui panel: http://$SERVER_IP:2053"
echo "2. Create VLESS Reality inbound on port 8443"
echo "3. Copy UUID, Public Key, Short ID to .env:"
echo "   nano /opt/bablo-vpn/.env"
echo "4. Restart: docker compose up -d"
echo ""
echo "========================================="
echo "Status: cd /opt/bablo-vpn && docker compose ps"
echo "Logs: cd /opt/bablo-vpn && docker compose logs -f"
echo "=========================================="
